Add converter
profcomff/converter-api pull request #1
Opened 2023-02-13 17:33 UTC by nmkazantsev

2023-02-13 17:50 UTC, grigoriev-semyon requested changes

2023-02-13 17:50 UTC, grigoriev-semyon commented on Dockerfile
> +
/static не добавлена в докер

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/models/base.py
> +class Base:
зачем здесь оно

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/routes/base.py
> +app.add_middleware(
CORS тебе тоже не нужен

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/routes/base.py
> +app.add_middleware(
это тоже не надо

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +'''
зачем оно

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +    if file == ...:
оно само кинет ошибку

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +    if file.content_type not in settings.CONTENT_TYPES:
content types не то
extension надо

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +    print(check_pdf_ok(result[1]))
логгинг или не надо

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/settings.py
> +    CORS_ALLOW_HEADERS: list[str] = ['*']
оно не надо

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/settings.py
> +    CONTENT_TYPES: List[str] = [
extension

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +    alph = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
string.acsii_letters

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +    name = hashlib.sha512(memory_file).hexdigest() + randomStr(10) + "." + ext
длина не 256

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +    path = abspath(settings.STATIC_FOLDER) + '/' + name
зачем абсолютный?

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +            raise HTTPException(415, f'File too large, {settings.MAX_SIZE} bytes allowed')
это можно проверить до сохранения

2023-02-13 17:50 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +    # await run (f"rm static/{name} ")
словарь бы key = extension, value = callable

2023-02-13 18:50 UTC, dyakovri commented on LICENSE
> +Copyright (c) 2022, Профком студентов физфака МГУ
Год 2023))

2023-02-13 18:51 UTC, dyakovri commented on Makefile
> +	alembic upgrade head
Кажется, тут БД не используется и не очень планируется, может выпилить все с этим связанное?

2023-02-13 18:52 UTC, dyakovri commented on file_converter/settings.py
> +    CORS_ALLOW_HEADERS: list[str] = ['*']
CORS надо
DB_DSN не надо

2023-02-13 18:54 UTC, dyakovri commented on file_converter/utils/converter.py
> +    name = hashlib.sha512(memory_file).hexdigest() + randomStr(10) + "." + ext
Зачем так сложно? Кажется, либо хэша, либо рандомной строки хватит
Я еще рекомендую файлу добавлять дату в начале в формате YYYY-MM-DD, позволит легко удалять старые файлы

2023-02-13 18:54 UTC, dyakovri commented on file_converter/utils/converter.py
> +'''
Забыли удалить?

2023-02-13 18:55 UTC, dyakovri commented on file_converter/utils/converter.py
> +'''
Забыли удалить?

2023-02-13 18:55 UTC, dyakovri commented on gunicorn_conf.py
> +import json
Этот файл не нужен

2023-02-13 18:55 UTC, dyakovri commented on requirements.txt
> +PyPDF3
Точно все нужны?

2023-02-13 18:56 UTC, dyakovri commented on requirements.txt
> +psycopg2-binary
Кажется, БД не используется

2023-02-13 18:56 UTC, dyakovri commented on static/.~lock.4e9cfe581da6d9dd7b947e36c5d870576c14c03d3a68916c016ac91491a7849146cf4ae1f19f1d74c4fd193fa0e895e62baf488f042d000341f1a4cc96bc9624aKIOBaANuF.docx#
> +,nikita,nikita-Aspire-A315-51,12.02.2023 22:30,file:///home/nikita/.config/libreoffice/4;
Что-то непонятное

2023-02-15 05:20 UTC, nmkazantsev commented on requirements.txt
> +PyPDF3
Не убрал то, что связано с бд, исправлю

2023-02-15 05:25 UTC, nmkazantsev commented on file_converter/utils/converter.py
> +'''
Нет, у нас потом, в светлом будущем, будет конвертация из картинок в пдф, а это рабочий код. С помощью него можно не тупо конвертировать, но и располагать картинки на странице пдф. Очень вероятно, что пригодится)

2023-02-15 05:27 UTC, nmkazantsev commented on file_converter/utils/converter.py
> +'''
Это тоже может понадобится, но оно не так ценно, его да, можно удалить))

2023-02-20 12:43 UTC, nmkazantsev commented on Dockerfile
> +
гит хаб тупит, восьмая строка выглядит уже так
COPY ./static /app/static/

2023-02-20 12:44 UTC, nmkazantsev commented on file_converter/settings.py
> +    CORS_ALLOW_HEADERS: list[str] = ['*']
db dns убрал

2023-02-21 16:43 UTC, grigoriev-semyon requested changes

2023-02-21 16:43 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        raise HTTPException(415, f'File too large, {settings.MAX_SIZE} bytes allowed')
го это в миддлвар

2023-02-21 16:43 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        requests.post(settings.PRINTER_URL, data={"file_link": result})
блочишь поток

2023-02-21 16:43 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        raise HTTPException(415, f'File too large, {settings.MAX_SIZE} bytes allowed')
413 вроде

2023-02-21 16:43 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +        await convert_runnables[extension[1:] + "_" + ext](name)
а зачем 1:
может просто convert[extension]?

2023-02-21 16:43 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +    fileName, extension = splitext(path)  # [0] - путь + имя, [1] - расширение
в некоторых случаях будет ломаться
extension = ....split(".")[-1]

2023-02-21 17:36 UTC, nmkazantsev commented on file_converter/utils/converter.py
> +        await convert_runnables[extension[1:] + "_" + ext](name)
А если мы потом захотим не только в пдф конвертить?...

2023-02-21 19:02 UTC, grigoriev-semyon commented on file_converter/utils/converter.py
> +        await convert_runnables[extension[1:] + "_" + ext](name)
Значит надо делать ключ из пары значений))

2023-02-27 17:09 UTC, grigoriev-semyon requested changes

2023-02-27 17:09 UTC, grigoriev-semyon commented on Dockerfile
> +RUN sudo apt install libtesseract-dev
лучше запускать команду вне докера

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +            pass
го  exception handler

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        to_ext: str, file: UploadFile = File(...), settings: Settings = Depends(get_settings), request: Request = None
to_ext в body тк это пост ручка

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +    if file.filename.split(".")[1] not in settings.EXTENTIONS:
-1

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        to_ext: str, file: UploadFile = File(...), settings: Settings = Depends(get_settings), request: Request = None
req лишний

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +class Convertable(ABC):
ABCMeta, metaclass=

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +        pass
raise NotImplementedError()

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +        s += alph[random.randint(0, len(alph) - 1)]
f строки лучше

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +    file_name, extension = splitext(path)  # [0] - путь + имя, [1] - расширение
split(".")[-1]

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +        await TYPES[extension].convert(name)
KeyError

2023-02-27 17:09 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +            return False
https://github.com/profcomff/print-api/commit/fb9e2ad6343f7ffe08f8044323df0a091a7e256b

2023-03-25 18:57 UTC, closed without merging