Доработал автотесты для конвертера
profcomff/converter-api pull request #3
Opened 2023-04-01 21:28 UTC by kosedo03

2023-04-02 16:37 UTC, grigoriev-semyon requested changes

2023-04-02 16:37 UTC, grigoriev-semyon commented on README.md
> +строки через shell возникнут проблемы с доступом к диреткории /static
typo

2023-04-02 16:37 UTC, grigoriev-semyon commented on README.md
> +**(!!Но затем вернуть всё к исходному!!)** :
без изменений кода никак?

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/routes/base.py
> +            500,
не найдено - 404 а не 500

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +
используется?

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +            pass
main непонятно

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +            f'Only {", ".join(settings.EXTENTIONS)} files allowed, but {file.content_type} received',
content-type и extension это разные вещи
мы используем только расширение

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/settings.py
> +    PRINTER_URL: str = "https://yandex.ru"
?

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
> +    return s
можно написать в одну строку

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        await run(f"rm {result}")
кажется неправильная команда

2023-04-02 16:37 UTC, grigoriev-semyon commented on file_converter/utils/convertable.py
раздели файл на несколько 
большой уже

2023-04-02 16:37 UTC, grigoriev-semyon commented on tests/conftest.py
> +@pytest.fixture(scope='session')
скоуп не нужен

2023-04-03 07:41 UTC, mrerro commented on README.md
> +**(!!Но затем вернуть всё к исходному!!)** :
добавте код на распознавание OC, и также поиск soffice.exe во всех стандартных местах где он может быть.

2023-04-07 23:21 UTC, kosedo03 commented on file_converter/settings.py
> +    PRINTER_URL: str = "https://yandex.ru"
Переписал, теперь просто JSON возвращаем

2023-04-07 23:21 UTC, kosedo03 commented on file_converter/routes/file.py
> +            pass
Убрал, вместе с printer_URL

2023-04-07 23:22 UTC, kosedo03 commented on file_converter/routes/file.py
> +
Нет

2023-04-07 23:22 UTC, kosedo03 commented on README.md
> +**(!!Но затем вернуть всё к исходному!!)** :
Добавил поиск по Program Files для винды, правда, время тестов увеличилось

2023-04-08 07:05 UTC, grigoriev-semyon requested changes

2023-04-08 07:05 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +    return {"status": "okay", "file_dir": f"{cd}{result}"}
отдавай сразу полную ссылку абсолютную

2023-04-08 07:05 UTC, grigoriev-semyon commented on file_converter/utils/check_pdf.py
> +    except Exception as e:
здесь точно except Exception? иили можно сузить класс ошибок? может SyntaxError?

2023-04-08 07:05 UTC, grigoriev-semyon commented on file_converter/utils/check_pdf.py
> +    f = open(full_file, "rb").read()
почему не в менеджере контекста?

2023-04-08 07:05 UTC, grigoriev-semyon commented on get_dir.py
> +"""Gets a cd for soffice.exe on Windows and /static directory independently from the OS"""
а почему это не иинкапсулировано в класс Convertable?

2023-04-08 07:05 UTC, grigoriev-semyon commented on get_dir.py
> +        if 'soffice.exe' in files:
ты пишешь про нестандартные пути 
а почему ты ищешь не по всем файлам?
зачем потом менять код?

2023-04-08 07:05 UTC, grigoriev-semyon commented on README.md
> +**(!!Но затем вернуть всё к исходному!!)** :
звучит плохо

2023-04-08 07:12 UTC, grigoriev-semyon commented on get_dir.py
> +"""Gets a cd for soffice.exe on Windows and /static directory independently from the OS"""
это значит что этот код можно выполнить один раз при инициализации класса Convertable.
Можно попробовать возвращать не строки
Можно в класс записать Callabble 
типа инициализируешь класс выполняя вот эту функцию да и записываешь в классовую переменную Callable.
там будет уже прописанная команда, но не будет файла
и чет типа command(filename) будет

2023-04-08 07:13 UTC, mrerro commented on README.md
> +**(!!Но затем вернуть всё к исходному!!)** :
get_dir.py должен же был как раз убрать этот пункт

2023-04-08 07:18 UTC, mrerro commented on get_dir.py
> +        if 'soffice.exe' in files:
тут смотря на сколько надо углубиться, но минимум надо проверить ProgramFiles, ProgramFiles(x86), %localappdata%/Programs, текущую директорию - вдруг portable подложили. И использовать переменные среды windows. Диск `C` не обязательно системный.

2023-04-08 10:32 UTC, mrerro commented on file_converter/utils/check_pdf.py
> +    except Exception as e:
Чем тут будет полезней сужение типов ошибок?

2023-04-08 10:54 UTC, grigoriev-semyon commented on file_converter/utils/check_pdf.py
> +    except Exception as e:
> Чем тут будет полезней сужение типов ошибок?

Ну сейчас оно на все говорит 415 
Не важно что кинуло ошибку - io или PdfFileReader, какую ошибку, может там не broken pdf?
Пусть лучше будет кидать 500, чем я буду смотреть логи и думать почему не грузит норм файл

2023-04-08 11:24 UTC, mrerro commented on file_converter/utils/check_pdf.py
> +    except Exception as e:
Вообще зачем эта функция тут? у нас идет проверка на pdf в print-api это функция скопирована оттуда, зачем она конвертеру? проверять что выдал либреофис?
Второе предложи тогда как гарантированно узнать какие ошибки можно получить за ранее? Когда фиксили проверку pdf в print-api то можно словить PyPdfError если это не pdf или ValueError если файл бит. Но выборка битости мала и есть шанс словить что то еще и как гарантировать что ты не пропустишь какую-нибудь дич?

2023-04-08 11:42 UTC, grigoriev-semyon commented on file_converter/utils/check_pdf.py
> +    except Exception as e:
Вообще действительно функцию можно отсюда убрать так как она уже есть в print-api

насчет второго хз, скорее всего только путем исследований так как насколько я помню дока там очень плохая(не написано что какие ошибки кидает)

2023-04-11 20:00 UTC, kosedo03 commented on file_converter/utils/check_pdf.py
> +    f = open(full_file, "rb").read()
Убрано вовсе

2023-04-11 20:01 UTC, kosedo03 commented on file_converter/utils/check_pdf.py
> +    except Exception as e:
Соглашусь, раз в принтере проверка на пдф уже есть, то убрано

2023-04-11 20:01 UTC, kosedo03 commented on get_dir.py
> +"""Gets a cd for soffice.exe on Windows and /static directory independently from the OS"""
Переделал в класс и функцию в функции

2023-04-11 20:02 UTC, kosedo03 commented on README.md
> +**(!!Но затем вернуть всё к исходному!!)** :
Добавил проход для шиндоус в Program Files, Program Files (x86). ProgramData и Users

2023-04-11 20:03 UTC, kosedo03 commented on file_converter/routes/file.py
> +    return {"status": "okay", "file_dir": f"{cd}{result}"}
Добавил в Settings ROOT_PATH, который из енв берет ссыль

2023-04-11 20:37 UTC, Temmmmmo reviewed
Что тут писать? Конец ревью.

2023-04-11 20:37 UTC, Temmmmmo commented on file_converter/settings.py
> +    ROOT_PATH: str = '/' + os.getenv('APP_NAME', '')
`ROOT_PATH: str = '/' + os.getenv('APP_NAME', '')` добавь сюда `| None`

2023-04-11 20:37 UTC, Temmmmmo commented on file_converter/utils/check_pdf.py
>          return False
Сделай короче:
`return exists(full_file)`

2023-04-11 20:37 UTC, Temmmmmo commented on get_dir.py
> +        cd = ext_d[:-2] + slash + 'static' + slash
Наверное, лучше f-строку тут сделать, читаемость плохая.

2023-04-11 20:37 UTC, Temmmmmo commented on get_dir.py
> +        cd = ext_d[:-2] + slash + 'static' + slash
Аналогично, f-строку

2023-04-11 20:37 UTC, Temmmmmo commented on get_dir.py
> +        self.direct = f.get('direct')
Ты в конструкторе присваиваешь значения полю command и полю direct этого класса. Однако эти поля не определены, добавь их.

2023-04-11 20:37 UTC, Temmmmmo commented on get_dir.py
> +    return get_command(OS, filename)
В класс GetCommand лучше добавить в виде метода, вроде ты больше нигде этим не пользуешься.

2023-04-11 20:37 UTC, Temmmmmo commented on get_dir.py
> +def get_command(OS: str, filename: str):
Туда же в класс в в виде метода положи.

2023-04-11 20:37 UTC, Temmmmmo commented on file_converter/utils/convertable.py
>      return ''.join(random.choice(alph) for i in range(n))
Я думаю, стоит эту функцию в отдельный файл пихнуть.

2023-04-11 21:23 UTC, kosedo03 commented on get_dir.py
> +        self.direct = f.get('direct')
не надо, само инициализирует все хорошо

2023-04-11 22:38 UTC, kosedo03 commented on file_converter/utils/convertable.py
>      return ''.join(random.choice(alph) for i in range(n))
пихнул

2023-04-11 22:38 UTC, kosedo03 commented on get_dir.py
> +def get_command(OS: str, filename: str):
сделал

2023-04-11 22:39 UTC, kosedo03 commented on get_dir.py
> +        self.direct = f.get('direct')
исправил, ввел валидацию

2023-04-11 22:40 UTC, kosedo03 commented on file_converter/settings.py
> +    ROOT_PATH: str = '/' + os.getenv('APP_NAME', '')
Ошибку выдает, __or__ не определен для str. Оставлю так.

2023-04-12 08:53 UTC, dyakovri commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Выпили папочку и ее в глобальный гитигнор
https://stackoverflow.com/a/7335487/20610418

2023-04-12 08:55 UTC, dyakovri commented on file_converter/settings.py
> +    STATIC_FOLDER: str = DirectoryPath | None
Перенеси над конфиг

2023-04-12 09:01 UTC, dyakovri commented on file_converter/settings.py
> +    ROOT_PATH: str = '/' + os.getenv('APP_NAME', '')
В типах данных используют именно вертикальную черту

2023-04-13 11:07 UTC, grigoriev-semyon requested changes

2023-04-13 11:07 UTC, grigoriev-semyon commented on file_converter/settings.py
> +    STATIC_FOLDER: str = DirectoryPath | None
```python 
STATIC_FOLDER: str = DirectoryPath | None
```
это дичь ибо ты присвоил класс в переменную которая должна быть строкового типа
```python 
STATIC_FOLDER:  DirectoryPath | None
```

2023-04-13 11:07 UTC, grigoriev-semyon commented on file_converter/utils/check_pdf.py
> +    return exists(full_file)
какой смысл в замене одной строки на одну строку? я вижу только минусы

2023-04-13 11:07 UTC, grigoriev-semyon commented on get_dir.py
> +        return {'command': command, 'direct': direct}
какой смысл запускать его каждый раз?
почему не сделать это при инициализации класса а потом уже отдавать то что есть?

2023-04-13 11:07 UTC, grigoriev-semyon commented on get_dir.py
> +class GetCommand:
а зачем этот класс? может можно без него? я просил просто переменную прокинуть в Convertable

2023-04-13 11:07 UTC, grigoriev-semyon commented on get_dir.py
> +        for i in paths:
for path in

2023-04-13 12:24 UTC, grigoriev-semyon requested changes

2023-04-13 12:24 UTC, grigoriev-semyon commented on Dockerfile
> +
в контейнере нет либры

2023-04-13 18:03 UTC, kosedo03 commented on file_converter/settings.py
> +    STATIC_FOLDER: str = DirectoryPath | None
заменил на str

2023-04-13 18:03 UTC, kosedo03 commented on file_converter/utils/check_pdf.py
> +    return exists(full_file)
убрал полностью, теперь напрямую в file

2023-04-13 18:04 UTC, kosedo03 commented on Dockerfile
> +
Добавил команду

2023-04-13 18:08 UTC, kosedo03 commented on get_dir.py
> +        return {'command': command, 'direct': direct}
в подклассах Convertable теперь добавлена функция, также удаление старых файлов перенес в подклассы вместо вызова непосредственно в file_convert

2023-04-14 12:31 UTC, grigoriev-semyon requested changes

2023-04-14 12:31 UTC, grigoriev-semyon commented on file_converter/exceptions.py
> +class HTTP_400_BAD_REQUEST(Exception):
название дичь

2023-04-14 12:31 UTC, grigoriev-semyon commented on file_converter/exceptions.py
> +        return f'{self.message}'
я думаю такое тут не надо

2023-04-14 12:31 UTC, grigoriev-semyon commented on file_converter/utils/libre.py
> +            raise HTTP_400_BAD_REQUEST
дичь
я попросил свой класс а не костыль с названием из http))

2023-04-14 12:33 UTC, grigoriev-semyon commented on file_converter/converters/convert.py
> +    old_name = f'{timestamp}_{_random_str}.{extension}'
почему не _old_name?

2023-04-14 12:33 UTC, grigoriev-semyon commented on file_converter/converters/convert.py
> +    path = f'{settings.STATIC_FOLDER}/{old_name}'
old_path

2023-04-14 12:34 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +        )
не будет такой же ошибки как сегодня упала
если расширение не указано
давай обработку на это и тест

2023-04-14 20:37 UTC, grigoriev-semyon requested changes

2023-04-14 20:37 UTC, grigoriev-semyon commented on file_converter/utils/libre.py
> +                raise HTTPException(status_code=400, detail='Posted file is corrupted')
дичь

2023-04-14 20:37 UTC, grigoriev-semyon commented on file_converter/routes/file.py
> +                                detail=f'Only {", ".join(settings.EXTENTIONS)} files are allowed.'
дичь

2023-04-14 20:37 UTC, grigoriev-semyon commented on file_converter/utils/libre.py
> +    raise ConvertError
дичь

2023-04-15 01:39 UTC, grigoriev-semyon approved these changes

2023-04-15 01:39 UTC, merged